### ISSUE TITLE
[View]랭킹페이지 작동 여부 

### ISSUE THREAD

**Issue by jeeeeeenno** [damdam6/RE-Habbit-ShinhanH#32]
## 에뮬레이터 작동 문제 
> 에뮬리에터 작동 문제로 인한 구현 여부 확인 불가 

<요청사항>
해당 코드 작동 하는지 확인 부탁드립니다 
>jeeeeeenno/Testing_For_ShinHan 의 
fead : [#73] 랭킹페이지 틀

로 파일 올려놓았습니다.

**Comment by bloblog** [comment]
확인해보니, 크기 문제로 화면에 뜨지 않는 이슈가 있어 화면에 뜰 수 있게끔 수정해봤습니다.
여기에 수정 파일 올릴테니 확인하시고 깃에 반영 부탁드려요!
그리고 사용한 라이브러리들도 pubspec.yaml 파일 종속성 부분에 추가해주세요~

[[수정] RankView_test.dart.zip](https://github.com/damdam6/RE-Habbit-ShinhanH/files/12567009/RankView_test.dart.zip)
